[package]
authors.workspace = true
autobins = false
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "trakkin-mappings-cli"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "trakkin-mappings"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
trakkin-mappings-corpus.workspace = true
trakkin-mappings-language.workspace = true
trakkin-mappings-ingestion.workspace = true

[dev-dependencies]
tempfile.workspace = true
